version: '3'
services:
  ldap:
    build: .
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ./certs:/container/service/slapd/assets/certs
    environment:
      - LDAP_TLS_VERIFY_CLIENT=try
      - LDAP_TLS_CRT_FILENAME=server.crt
      - LDAP_TLS_KEY_FILENAME=server.key
      # - LDAP_TLS_CA_CRT_FILENAME=the-ca.crt
